package ar.edu.unlam.pb2.callcenter;

public enum Provincia {
	BUENOS_AIRES,CAPITAL_FEDERAL,
	CATAMARCA,CHACO,CHUBUT,CÓRDOBA,
	CORRIENTES,ENTRE_RÍOS,FORMOSA,JUJUY,
	LA_PAMPA,LA_RIOJA,MENDOZA,MISIONES,
	NEUQUÉN,RÍO_NEGRO,SALTA,SAN_JUAN,SAN_LUIS,
	SANTA_CRUZ,
	SANTA_FE,
	SANTIAGO_DEL_ESTERO,
	TIERRA_DEL_FUEGO,
	TUCUMÁN,
}
